Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Max: 40

Metrics/LineLength:
  Max: 120
